# Generated by Django 5.1.1 on 2024-09-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
