# Generated by Django 5.1.1 on 2024-09-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_created',
        ),
    ]
